name: test

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Switch to PHP 8.1
        run: |-
          sudo update-alternatives --set php /usr/bin/php8.1

      - name: Validate composer.json and composer.lock
        run: |-
          composer validate

      - name: Setup Symfony
        env:
          APP_ENV: prod
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: |-
          composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Run tests
        env:
          APP_ENV: prod
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: |-
          composer install
          composer run-script test
